services:
  cups:
    image: jysky007/cups:v1
    container_name: cups
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ~/airprint_data/config:/config
      - ~/airprint_data/services:/services
      - /mnt/docker/cups/scripts:/root
      #把airprint-generate.py  printer-update.sh  run_cups.sh 放到/mnt/docker/cups/scripts文件夹里面
    environment:
      - CUPSADMIN=admin
      - CUPSPASSWORD=adminadmin
